name: Run Linux Tests

on:
  push:
    paths:
      - '.github/workflows/'
      - '*.py'
  pull_request:
    paths:
      - '.github/workflows/'
      - '*.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  pip install -r requirements.txt

      - name: Run test
        run: |
          echo ============================================
          echo Running Tests
          python patcher-yml.py  testdata/testdata.elf example.yml
          echo ============================================
